alias editsource='vim ~/.bash_aliases; source ~/.bashrc'
alias ez='~/ez.sh'
alias ll='ls -la --color'
alias lol='ls -la | lolcat -s 10'
alias ngrok='~/ngrok/ngrok'
alias sbrc='source ~/.bashrc'
alias watchstarwars='telnet towel.blinkenlights.nl'
